#! /bin/sh

while read -r line
do
	echo "<---------- User ------------->"
	printf "Login : "
	printf $line | cut -d ':' -f 1
	printf "UID : "
	printf $line | cut -d ':' -f 3
	printf "Path : "
	printf $line | cut -d ':' -f 7
	echo "<----------------------------->"
done < "/etc/passwd"
