#! /bin/sh

# Modifier le fichier crontab de root : sudo crontab -e
# 0 0 * * * /home/coucou/Lab/04
# 
# Solution securite :
# Au premier lancement, creer le fichier contenant le hash (EN ROOT) :
#	echo `md5sum /etc/crontab` >> /etc/.crontab.hash

if [ -f /etc/.crontab.hash ]
then
	original=`head -n 1 /etc/.crontab.hash | cut -d ' ' -f 1`
	current=`md5sum /etc/crontab | cut -d ' ' -f 1`

	if [ $original != $current ]
	then
		echo "The file /etc/crontab has been modified, a new hash has been created" | mailx -s "Your file /etc/crontab" root
		rm -rf /etc/.crontab.hash
		echo `md5sum /etc/crontab` >> /etc/.crontab.hash
	fi
else
	echo "The verification file /etc/.crontab.hash was not found when the checking of the /etc/crontab file. Please verify the file" | mailx -s "The file .crontab.hash was not found" root
fi

# First version

#original="8f111d100ea459f68d333d63a8ef2205"
#current=`md5sum /etc/crontab | cut -d ' ' -f1`
#
#if [ $original != $current ]
#then
#	echo "The file /etc/crontab has been modified, a new hash has been created" | mailx -s "Your file /etc/crontab" root
#fi
